name: Sheep
main: Sheep\SheepPlugin
version: 5.0.1
api: [3.0.0-ALPHA7]

author: KnownUnown
description: A plugin for [installing, uninstalling, viewing] other plugins.
website: https://www.github.com/KnownUnown/Sheep