<?php


namespace Sheep\Utils;


class Lockfile {
	private $file;
	private $data;
	private $plugins;

	public function __construct(string $file = "sheep.lock") {
		$this->file = fopen($file, "c+");
		$this->data = json_decode(@fread($this->file, filesize($file)), true);

		if(!@$this->data["_readme"]) {
			$this->data = [ "_readme" => [
				"Generated by Sheep on " . date("F j, Y, g:i a") . ".",
			], "plugins" => []];
		}
		$this->plugins = &$this->data["plugins"];
	}

	public function addPlugin(array $plugin) {
		$this->plugins[strtolower($plugin["name"])] = $plugin;
	}

	public function getPlugin(string $plugin) {
		return $this->plugins[$plugin];
	}

	public function removePlugin(string $plugin) {
		unset($this->plugins[$plugin]);
	}

	public function exists(string $plugin) : bool {
		return @$this->plugins[strtolower($plugin)] !== null;
	}

	public function save() {
		ftruncate($this->file, 0);
		fseek($this->file, 0);
		fwrite($this->file, json_encode($this->data, JSON_PRETTY_PRINT));
	}

	public function __destruct() {
		$this->save();
	}
}