<?php
declare(strict_types=1);


namespace Sheep\Store;


class FileStore extends MemoryStore {
	private $filename, $data;

	public function __construct(string $filename) {
		$this->filename = $filename;
		if (file_exists($filename)) {
			$this->data = json_decode(file_get_contents($filename), true);
		} else {
			$this->data = [ // other elements may be added for future use
				"_readme" => "This file was generated by Sheep on " . date("F j, Y, g:i a") . ".",
				"plugins" => [],
			];
		}
		$this->plugins = &$this->data["plugins"];
		$this->persist();
	}

	public function persist() {
		file_put_contents($this->filename, json_encode($this->data, JSON_PRETTY_PRINT));
	}
}