<?php
/**
 * Copyright (c) 2017, 2018 KnownUnown
 *
 * This file is part of Sheep.
 *
 * Sheep is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Sheep is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

declare(strict_types=1);


namespace Sheep\Store;


class FileStore extends MemoryStore {
	private $filename, $data;

	public function __construct(string $filename) {
		$this->filename = $filename;
		if(file_exists($filename)) {
			$this->data = json_decode(file_get_contents($filename), true);
		} else {
			$this->data = [ // other elements may be added for future use
				"_readme" => "This file was generated by Sheep on " . date("F j, Y, g:i a") . ".",
				"plugins" => [],
			];
		}
		$this->plugins = &$this->data["plugins"];
		$this->persist();
	}

	public function persist() {
		file_put_contents($this->filename, json_encode($this->data, JSON_PRETTY_PRINT));
	}
}
